" Editor behavior

" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'pearofducks/ansible-vim'
Plugin 'rust-lang/rust.vim'
call vundle#end()            " required
filetype plugin indent on



set autoindent
set smartindent
set ttyfast
set et
set nobackup
set listchars=tab:▸\ ,eol:¬
set list
set comments=b:#,:%,fb:-,n:>,n:)
set noerrorbells
set ignorecase
set modelines=0
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
filetype on " enable filetype detection
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
autocmd Filetype python setlocal ts=4 sw=4 expandtab
"set printoptions=paper:letter

" Editor looks
set laststatus=2
set ruler
set showcmd
set showmode
set number
set title
set scrolloff=3
set hlsearch
syntax on
set t_Co=256
colorscheme jellybeans
hi StatusLine ctermbg=black ctermfg=white
set cursorline

" Keyboard mappings
let mapleader = ","
nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>
nnoremap <F3> :set paste!<CR>
nnoremap <F5> :set list!<CR>
" sort visually hilighted lines
map <F9> :sort<CR>
map Y y$

" mess with the noobs
noremap <Left> <NOP>
noremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
