" Editor behavior

set nocompatible
filetype plugin indent on

" tab stuff -- commented out since installing sleuth
" set autoindent
" set smartindent
" set tabstop=4
" set shiftwidth=4
" set softtabstop=4
" set expandtab
" autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
" autocmd Filetype ansible setlocal ts=2 sw=2 expandtab
" autocmd Filetype python setlocal ts=4 sw=4 expandtab

" a probably incomplete list of plugins in my pack/*/start dir
" challenger-deep (theme)
" fzf
" nord (theme)
" solarized (theme)
" tagbar
" vim-colors-xcode (theme)
" vim-commentary
" vim-endwise
" vim-signify
" vim-sleuth
" vim-surround
" vim-terraform

set ttyfast
set et
set nobackup
set comments=b:#,:%,fb:-,n:>,n:)
set noerrorbells
set ignorecase
set smartcase
set modelines=0
set backspace=indent,eol,start
filetype on " enable filetype detection
set tags=tags;/
set mouse=a
set autoread
set autoindent

" Editor looks
set laststatus=2
set ruler
set number
set title
set scrolloff=3
set sidescrolloff=5
set incsearch
set hlsearch
syntax on
set background=dark
set termguicolors
colorscheme xcodedark
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set cursorline
" set noshowmode
set showcmd
" let g:lightline = {'colorscheme': 'wombat',}
" set listchars=tab:▸\ ,eol:¬
" set list
set updatetime=100 " for async git gutter updates
let g:signify_sign_add    = '┃'
let g:signify_sign_change = '┃'
let g:signify_sign_delete = '•'

let g:signify_sign_show_count = 0 " Don’t show the number of deleted lines.

" Keyboard mappings
let mapleader = ","
nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>
nnoremap <F3> :set paste!<CR>
nnoremap <F6> :set list!<CR>
nnoremap <F4> :set relativenumber!<CR>
nnoremap <C-x> :bnext<CR>
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!
" sort visually hilighted lines
map <leader>s :sort<CR>
map Y y$
nmap <leader>t :TagbarToggle<CR>
