(add-to-list 'load-path "~/.emacs.d/")
(add-to-list 'load-path "~/.emacs.d/plugins/")
(add-to-list 'load-path "~/.emacs.d/plugins/expand-region/")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/emacs-color-theme-solarized")
(add-to-list 'auto-mode-alist '("Rakefile$" . ruby-mode))
(require 'ace-jump-mode)
(define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
(require 'ido)
(ido-mode t)
(setq ido-enable-flex-matching t)
(require 'copy-line)
(define-key global-map (kbd "C-c k") 'kill-whole-line)
(define-key global-map (kbd "C-c C-k") 'copy-line)
(require 'expand-region)
(global-set-key (kbd "C-=") 'er/expand-region)
(add-to-list 'auto-mode-alist '("/mutt" . mail-mode))
(if window-system
    (load-theme 'solarized-dark t))
