export HISTCONTROL=ignoredups:ignorespace
export HISTIGNORE="&:ls:[bf]g:exit"
export HISTORY=5000
export HISTTIMEFORMAT="%F %T "
export LANG=en_US.utf-8
export LANGUAGE=en_US.utf-8
export LC_ALL=en_US.utf-8
export LC_COLLATE=C
export LC_CTYPE=en_US.utf-8
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
export MAILCHECK=20
export XDG_CONFIG_DIRS=/etc/xdg:/afs/csail.mit.edu/u/j/jahl/.config

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
