export BROWSER=firefox
export CLICOLOR=1
export EDITOR=emacs
export HISTCONTROL=ignoredups:ignorespace
export HISTIGNORE="&:ls:[bf]g:exit"
export HISTORY=5000
export HISTTIMEFORMAT="%F %T "
export LANG=en_US.utf-8
export LANGUAGE=en_US.utf-8
export LC_ALL=en_US.utf-8
export LC_COLLATE=C
export LC_CTYPE=en_US.utf-8
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
export LSCOLORS='ExGxFxdxCxDxDxBxBxExEx'
export MAILCHECK=20
export PAGER=/usr/bin/less
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
export TERM=xterm-256color
export XDG_CONFIG_DIRS=/etc/xdg:/afs/csail.mit.edu/u/j/jahl/.config
export PATH=${PATH}:/usr/local/packer

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi