export LANG=en_US.utf-8
export LANGUAGE=en_US.utf-8
export LC_CTYPE=en_US.utf-8
export LC_COLLATE=C
export LC_ALL=en_US.utf-8
export PATH=~/bin:${PATH}:/sbin:/usr/sbin:/usr/local/packer
export XDG_CONFIG_DIRS=/etc/xdg:/afs/csail.mit.edu/u/j/jahl/.config
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
